FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages

COPY ./apps/backend ./apps/backend

RUN bun install
RUN DATABASE_URL=${DATABASE_URL} bun run db:generate

CMD ["bun", "run", "start:backend"]